name: Package OSX

runs:
  using: "composite"
  steps:

  - name: Download OSX Artifacts
    uses: actions/download-artifact@v4
    with:
      path: binaries-${{ env.gudrunVersion }}-osx
      pattern: binaries-${{ env.gudrunVersion }}-osx-*

  - name: Create FAT Binaries
    shell: bash
    run: |
      set -ex
      for BINARY in binaries-${{ env.gudrunVersion }}-osx/binaries-${{ env.gudrunVersion }}-osx-silicon/* do
      do
        install_name_tool -change /usr/lib/libz.1.dylib /opt/homebrew/opt/zlib/lib/libz.1.dylib binaries-${{ env.gudrunVersion }}-osx/binaries-${{ env.gudrunVersion }}-osx-silicon/BINARY
        lipo -create binaries-${{ env.gudrunVersion }}-osx/binaries-${{ env.gudrunVersion }}-osx-intel/BINARY binaries-${{ env.gudrunVersion }}-osx/binaries-${{ env.gudrunVersion }}-osx-silicon/BINARY -output binaries-${{ env.gudrunVersion }}-osx-fat/BINARY
      done

  - name: Create Zip
    shell: bash
    run: |
      set -ex
      zip -9rv binaries-${{ env.gudrunVersion }}-osx-fat.zip binaries-${{ env.gudrunVersion }}-osx-fat/

  - name: Upload Raw Build Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: binaries-${{ env.gudrunVersion }}-osx-fat
      path: binaries-${{ env.gudrunVersion }}-osx-fat