parameters:
  - name: extraflags
    default: ''

steps:
  - bash: |
      set -ex
      brew update-reset
      brew install hdf5 ninja
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      mkdir build
      cd build
      cmake ../ -G Ninja ${{ parameters.extraflags }}
      ninja
      ninja install
    displayName: 'Build'
