parameters:
  - name: hdf5tag
    default: hdf5-1_10_7
  - name: extraflags
    default: ''

steps:
  - bash: |
      set -ex
      brew update-reset
      brew install ninja
    displayName: 'Install Prerequisites'
  - bash: |
      wget https://github.com/disorderedmaterials/HDF5/releases/download/${{ parameters.hdf5tag }}/${{ parameters.hdf5tag }}-osx.zip
      unzip ${{ parameters.hdf5tag }}-linux.zip
      ls
    displayName: 'Download HDF5 Artifacts'
  - bash: |
      set -ex
      mkdir build
      cd build
      cmake ../ -G Ninja -DCMAKE_Fortran_COMPILER:string="gfortran-9" -DLOCAL_STATIC_HDF5:bool=True -DHDF5_DIR:path=./${{ parameters.hdf5tag }} ${{ parameters.extraflags }}
      ninja
      ninja install
    displayName: 'Build'
