parameters:
  - name: hdf5tag
    default: hdf5-1_10_7
  - name: extraflags
    default: ''

steps:
  - bash: |
      set -ex
      sudo apt-get update -q
      sudo apt-get install ninja-build gfortran
    displayName: 'Install Prerequisites'
  - bash: |
      HDF5_ZIP="${{ parameters.hdf5tag }}-linux.zip"
      echo "HDF5 zip to acquire is ${HDF5_ZIP}"
      wget https://github.com/disorderedmaterials/HDF5/releases/download/hdf5-1_10_7/${HDF5_ZIP}
      unzip ${HDF5_ZIP}
    displayName: 'Get HDF5'
  - bash: |
      set -ex
      HDF5_DIR="$(pwd)/${{ parameters.hdf5tag }}"
      mkdir build
      cd build
      cmake ../ -G "Ninja" -DHDF5_DIR:path=${HDF5_DIR} ${{ parameters.extraflags }}
      ninja
      ninja install
    displayName: 'Build'
