parameters:
  - name: extraflags
    default: ''

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: |
      choco install -y mingw
    displayName: 'Install Prerequisites'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      mkdir build
      cd build
      cmake ../ -G "MinGW Makefiles" -DBUILD_ZLIB:bool=True ${{ parameters.extraflags }}
      cmake --build . --config Release
      cmake --install .
    displayName: 'Build'
