parameters:
  - name: hdf5tag
    default: hdf5-1_10_7
  - name: extraflags
    default: ''

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: |
      choco install -y mingw
    displayName: 'Install Prerequisites'
  - bash: |
      wget https://github.com/disorderedmaterials/HDF5/releases/download/${{ parameters.hdf5tag }}/${{ parameters.hdf5tag }}-windows.zip
      7z x ${{ parameters.hdf5tag }}-linux.zip
      ls
    displayName: 'Download HDF5 Artifacts'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      mkdir build
      cd build
      cmake ../ -G "MinGW Makefiles" -DLOCAL_STATIC_HDF5:bool=True -DHDF5_DIR:path=./${{ parameters.hdf5tag }} ${{ parameters.extraflags }}
      cmake --build . --config Release
      cmake --install .
    displayName: 'Build'
