parameters:
  - name: suffix
    default: linux
  - name: zipcommand
    default: "zip -9rv"
  - name: packageMinGWLibs
    default: false
    type: boolean
steps:
  - bash: |
      set -ex
      MINGWLIB="C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\\"
      cp $MINGWLIB\libquadmath-0.dll bin/
      cp $MINGWLIB\libwinpthread-1.dll bin/
      cp $MINGWLIB\libgcc_s_seh-1.dll bin/
    condition: eq('${{ parameters.useMinGW }}', true)
    displayName: 'Package MinGW Libs'
  - bash: |
      set -ex
      VERSION=$(cat version)
      mkdir binaries-${VERSION}-${{ parameters.suffix }}
      cp bin/* binaries-${VERSION}-${{ parameters.suffix }}
      ${{ parameters.zipcommand }} binaries-${VERSION}-${{ parameters.suffix }}.zip binaries-${VERSION}-${{ parameters.suffix }}/
    displayName: 'Create Binaries Zip'
  - bash: |
      set -ex
      mkdir packages
      mv binaries-*.zip packages
    displayName: 'Move Artifacts'
