parameters:
  - name: suffix
    default: linux
  - name: zipcommand
    default: "zip -9rv"

steps:
  - bash: |
      set -ex
      VERSION=$(cat version)
      mkdir binaries-${VERSION}-${{ parameters.suffix }}
      cp bin/* binaries-${VERSION}-${{ parameters.suffix }}
      ${{ parameters.zipcommand }} binaries-${VERSION}-${{ parameters.suffix }}.zip binaries-${VERSION}-${{ parameters.suffix }}/
    displayName: 'Create Binaries Zip'
  - bash: |
      set -ex
      mkdir packages
      mv binaries-*.zip packages
    displayName: 'Move Artifacts'
