steps:
  - bash: |
      set -ex
      VERSION=$(cat version)
      mkdir binaries-${VERSION}-linux
      cp bin/* binaries-${VERSION}-linux
      ldd bin/gudrun_dcs
    displayName: 'Create Binaries Zip'
  - bash: |
      set -ex
      mkdir packages
      mv binaries-*.zip packages
    displayName: 'Move Artifacts'
