trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .azure-pipelines/pr.yml
    - .azure-pipelines/release.yml

pr: none

stages:
  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'linux'
        displayName: 'Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux.yml
      - job: 'osx'
        displayName: 'OSX'
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
      - job: 'windows'
        displayName: 'Windows'
        condition: eq(1,0)
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows.yml
