trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - "*"
  paths:
    exclude:
    - examples/*
    - .azure-pipelines/continuous.yml
    - .azure-pipelines/release.yml

stages:
  # Build Executables
  - stage: "build"
    displayName: "Build"
    jobs:
      - job: "linux"
        displayName: "Ubuntu
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "build/"
              ArtifactName: "linux-tests"
            displayName: "Publish Threaded Test Artifacts"
      - job: "osx"
        displayName: "OSX"
        pool:
          vmImage: "macos-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
          - template: templates/package-osx.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: "osx-artifacts"
            displayName: "Publish OSX Artifacts"
      - job: "windows"
        displayName: "Windows"
        pool:
          vmImage: "windows-latest"
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows.yml
          - template: templates/package-windows.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: "windows-artifacts"
            displayName: "Publish Windows Artifacts"

