trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - "*"
  paths:
    exclude:
    - .azure-pipelines/continuous.yml
    - .azure-pipelines/release.yml

variables:
  hdf5tag: hdf5-1_10_7

stages:
  # Build and Package Executables
  - stage: 'build'
    displayName: 'Build and Package'
    jobs:
      - job: 'linux'
        displayName: 'Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux.yml
            parameters:
              hdf5tag: $(hdf5tag)
          - template: templates/package-binaries.yml
            parameters:
              suffix: 'linux'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
      - job: 'osx'
        displayName: 'OSX'
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
            parameters:
              hdf5tag: $(hdf5tag)
          - template: templates/package-binaries.yml
            parameters:
              suffix: 'osx'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'
      - job: 'windows'
        displayName: 'Windows'
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-windows.yml
            parameters:
              hdf5tag: $(hdf5tag)
          - template: templates/package-binaries.yml
            parameters:
              suffix: 'windows'
              zipcommand: "7z a"
              packageMinGWLibs: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "packages/"
              ArtifactName: 'windows-artifacts'
            displayName: 'Publish Windows Artifacts'
